version: '3.8'

services:
  database:
    container_name: database
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-arporb}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:${REDIS_VERSION:-6}-alpine
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-your_secure_password}
    volumes:
      - redis_data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    networks:
      - backend

  nginx:
    container_name: nginx
    image: nginx:1.25-alpine
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    ports:
      - "8080:80"
    networks:
      - backend
    depends_on:
      - php-fpm

volumes:
  database_data:
  redis_data:

networks:
  backend:
